// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// disperse
IntegerVector disperse(IntegerVector a, int Rdispersal, int grid);
RcppExport SEXP _ecoevosimulator_disperse(SEXP aSEXP, SEXP RdispersalSEXP, SEXP gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type Rdispersal(RdispersalSEXP);
    Rcpp::traits::input_parameter< int >::type grid(gridSEXP);
    rcpp_result_gen = Rcpp::wrap(disperse(a, Rdispersal, grid));
    return rcpp_result_gen;
END_RCPP
}
// simulatorCpp
List simulatorCpp(Rcpp::NumericMatrix Topo, Rcpp::NumericMatrix NCI, int grid, int Nt, int timestep, double sigmaGtopo, double sigmaZtopo, double sigmaGnci, double sigmaZnci, double Pdeath, int Ns, int Rpollination, int Rdispersion, bool determinist);
RcppExport SEXP _ecoevosimulator_simulatorCpp(SEXP TopoSEXP, SEXP NCISEXP, SEXP gridSEXP, SEXP NtSEXP, SEXP timestepSEXP, SEXP sigmaGtopoSEXP, SEXP sigmaZtopoSEXP, SEXP sigmaGnciSEXP, SEXP sigmaZnciSEXP, SEXP PdeathSEXP, SEXP NsSEXP, SEXP RpollinationSEXP, SEXP RdispersionSEXP, SEXP deterministSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Topo(TopoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type NCI(NCISEXP);
    Rcpp::traits::input_parameter< int >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< int >::type Nt(NtSEXP);
    Rcpp::traits::input_parameter< int >::type timestep(timestepSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaGtopo(sigmaGtopoSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaZtopo(sigmaZtopoSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaGnci(sigmaGnciSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaZnci(sigmaZnciSEXP);
    Rcpp::traits::input_parameter< double >::type Pdeath(PdeathSEXP);
    Rcpp::traits::input_parameter< int >::type Ns(NsSEXP);
    Rcpp::traits::input_parameter< int >::type Rpollination(RpollinationSEXP);
    Rcpp::traits::input_parameter< int >::type Rdispersion(RdispersionSEXP);
    Rcpp::traits::input_parameter< bool >::type determinist(deterministSEXP);
    rcpp_result_gen = Rcpp::wrap(simulatorCpp(Topo, NCI, grid, Nt, timestep, sigmaGtopo, sigmaZtopo, sigmaGnci, sigmaZnci, Pdeath, Ns, Rpollination, Rdispersion, determinist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ecoevosimulator_disperse", (DL_FUNC) &_ecoevosimulator_disperse, 3},
    {"_ecoevosimulator_simulatorCpp", (DL_FUNC) &_ecoevosimulator_simulatorCpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_ecoevosimulator(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
