// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// disperse
IntegerVector disperse(IntegerVector a, int d, int xmin, int xmax, int ymin, int ymax);
RcppExport SEXP _ecoevosimulator_disperse(SEXP aSEXP, SEXP dSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP yminSEXP, SEXP ymaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< int >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< int >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< int >::type ymax(ymaxSEXP);
    rcpp_result_gen = Rcpp::wrap(disperse(a, d, xmin, xmax, ymin, ymax));
    return rcpp_result_gen;
END_RCPP
}
// forestgapdynamics
NumericMatrix forestgapdynamics(int grid, int radius, double probability);
RcppExport SEXP _ecoevosimulator_forestgapdynamics(SEXP gridSEXP, SEXP radiusSEXP, SEXP probabilitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< int >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< double >::type probability(probabilitySEXP);
    rcpp_result_gen = Rcpp::wrap(forestgapdynamics(grid, radius, probability));
    return rcpp_result_gen;
END_RCPP
}
// product_environmental_matrix
NumericMatrix product_environmental_matrix(double gradientlim, int length);
RcppExport SEXP _ecoevosimulator_product_environmental_matrix(SEXP gradientlimSEXP, SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type gradientlim(gradientlimSEXP);
    Rcpp::traits::input_parameter< int >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(product_environmental_matrix(gradientlim, length));
    return rcpp_result_gen;
END_RCPP
}
// simulatorCpp
List simulatorCpp(int grid, int Ngen, double muG, double sigmaG, double muE, double sigmaE, double Elim, int seedlings, int dispersal, int gapradius, double fallprobability, double death, bool viability_deterministic);
RcppExport SEXP _ecoevosimulator_simulatorCpp(SEXP gridSEXP, SEXP NgenSEXP, SEXP muGSEXP, SEXP sigmaGSEXP, SEXP muESEXP, SEXP sigmaESEXP, SEXP ElimSEXP, SEXP seedlingsSEXP, SEXP dispersalSEXP, SEXP gapradiusSEXP, SEXP fallprobabilitySEXP, SEXP deathSEXP, SEXP viability_deterministicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< int >::type Ngen(NgenSEXP);
    Rcpp::traits::input_parameter< double >::type muG(muGSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaG(sigmaGSEXP);
    Rcpp::traits::input_parameter< double >::type muE(muESEXP);
    Rcpp::traits::input_parameter< double >::type sigmaE(sigmaESEXP);
    Rcpp::traits::input_parameter< double >::type Elim(ElimSEXP);
    Rcpp::traits::input_parameter< int >::type seedlings(seedlingsSEXP);
    Rcpp::traits::input_parameter< int >::type dispersal(dispersalSEXP);
    Rcpp::traits::input_parameter< int >::type gapradius(gapradiusSEXP);
    Rcpp::traits::input_parameter< double >::type fallprobability(fallprobabilitySEXP);
    Rcpp::traits::input_parameter< double >::type death(deathSEXP);
    Rcpp::traits::input_parameter< bool >::type viability_deterministic(viability_deterministicSEXP);
    rcpp_result_gen = Rcpp::wrap(simulatorCpp(grid, Ngen, muG, sigmaG, muE, sigmaE, Elim, seedlings, dispersal, gapradius, fallprobability, death, viability_deterministic));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ecoevosimulator_disperse", (DL_FUNC) &_ecoevosimulator_disperse, 6},
    {"_ecoevosimulator_forestgapdynamics", (DL_FUNC) &_ecoevosimulator_forestgapdynamics, 3},
    {"_ecoevosimulator_product_environmental_matrix", (DL_FUNC) &_ecoevosimulator_product_environmental_matrix, 2},
    {"_ecoevosimulator_simulatorCpp", (DL_FUNC) &_ecoevosimulator_simulatorCpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_ecoevosimulator(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
