# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Build gradient
#' 
#' @description
#' C++ code to build environmental gradients
#' 
#' @name build_gradient
#' 
#' @param gradientlim double. Environmental gradient size
#' @param length int. Number of cells
#' 
#' @examples
#' build_gradient(10, 10)
#' 
#' @export
build_gradient <- function(gradientlim, length) {
    .Call(`_ecoevosimulator_build_gradient`, gradientlim, length)
}

#' @title Disperse
#' 
#' @description
#' C++ code for dispersal
#' 
#' @name disperse
#' 
#' @param a int. Final dispesal position
#' @param d int. Dispersal distance
#' @param xmin int. Minimum cell coordinate
#' @param xmax int. Maximum cell coordinate
#' 
#' @examples
#' disperse(10, 10)
#' 
#' @export
disperse <- function(a, d, xmin, xmax) {
    .Call(`_ecoevosimulator_disperse`, a, d, xmin, xmax)
}

#' @title simulator C++
#' 
#' @description
#' Eco-evolutionary simulator in C++.
#' 
#' @name simulatorCpp
#' 
#' @param Nind int. Number of individuals
#' @param Ngen int. Number of generations
#' @param muG double. Mean of genetic values
#' @param sigmaG double. Variance of genetic values
#' @param muE double. Mean of environmental values
#' @param sigmaE double. Variance of environmental values
#' @param Elim double. Environmental gradient size
#' @param seedlings int. Number of seedlings per cell
#' @param dispersal int. Dispersal distance in cells
#' @param viability_deterministic bool. Deterministic or probabilistic vaibility
#' 
#' @return A lsit.
#' 
#' @examples
#' simulator()
#' 
#' @export
simulatorCpp <- function(Nind = 50L, Ngen = 50L, muG = 0, sigmaG = 1, muE = 0, sigmaE = 1, Elim = 10, seedlings = 4L, dispersal = 1L, viability_deterministic = TRUE) {
    .Call(`_ecoevosimulator_simulatorCpp`, Nind, Ngen, muG, sigmaG, muE, sigmaE, Elim, seedlings, dispersal, viability_deterministic)
}

