# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Disperse
#' 
#' @description
#' C++ code for dispersal
#' 
#' @name disperse
#' 
#' @param a IntegerVector. Final dispesal positions
#' @param Rdispersal int. Dispersal radius in cells
#' @param grid int. Number of cell per side of the matrix
#' 
#' @examples
#' disperse(c(10, 10), 2, 20)
#' 
#' @export
disperse <- function(a, Rdispersal, grid) {
    .Call(`_ecoevosimulator_disperse`, a, Rdispersal, grid)
}

#' @title Forest gap dynamics
#' 
#' @description
#' C++ code for forest gap dynamics
#' 
#' @name forestgapdynamics
#' 
#' @param grid int.Number of cell per side of the matrix
#' @param Pfall double. Treefall probability
#' @param Rgaps int. Treefall gaps radius
#' 
#' @examples
#' forestgapdynamics(20, 2, 0.01)
#' 
#' @export
forestgapdynamics <- function(grid, Pfall, Rgaps) {
    .Call(`_ecoevosimulator_forestgapdynamics`, grid, Pfall, Rgaps)
}

#' @title simulator C++
#' 
#' @description
#' Eco-evolutionary simulator in C++.
#' 
#' @name simulatorCpp
#' 
#' @param grid int. Number of cell per side of the matrix
#' @param Nt int. Number of time steps
#' @param Topography matrix. Environmental matrix
#' @param muG double. Mean of genetic values
#' @param sigmaG double. Variance of genetic values
#' @param muE double. Mean of environmental values
#' @param sigmaE double. Variance of environmental values
#' @param Pfall double. Treefall probability
#' @param Rgaps int. Treefall gaps radius
#' @param Pdeath double. Background mortality probability
#' @param Ns int. Number of seedlings per cell
#' @param Rdispersal int. Dispersal radius in cells
#' @param determinist bool. Deterministic or probabilistic vaibility
#' 
#' @return A lsit.
#' 
#' @examples
#' simulatorCpp(Topography = sinusoidalTopography(grid = 10, Elim = 5, amplitude = 0.01))
#' 
#' @export
simulatorCpp <- function(Topography, grid = 10L, Nt = 50L, muG = 0, sigmaG = 1, muE = 0, sigmaE = 1, Pfall = 0.01, Rgaps = 2L, Pdeath = 0.1, Ns = 4L, Rdispersal = 1L, determinist = TRUE) {
    .Call(`_ecoevosimulator_simulatorCpp`, Topography, grid, Nt, muG, sigmaG, muE, sigmaE, Pfall, Rgaps, Pdeath, Ns, Rdispersal, determinist)
}

