# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Disperse
#' 
#' @description
#' C++ code for dispersal
#' 
#' @name disperse
#' 
#' @param a IntegerVector. Final dispesal positions
#' @param d int. Dispersal distance
#' @param xmin int. Minimum row
#' @param xmax int. Maximum row
#' @param ymin int. Minimum column
#' @param ymax int. Maximum column
#' 
#' @examples
#' disperse(c(10, 10), 2, 0, 20, 0, 20)
#' 
#' @export
disperse <- function(a, d, xmin, xmax, ymin, ymax) {
    .Call(`_ecoevosimulator_disperse`, a, d, xmin, xmax, ymin, ymax)
}

#' @title Forest gap dynamics
#' 
#' @description
#' C++ code for forest gap dynamics
#' 
#' @name forestgapdynamics
#' 
#' @param grid int.Number of cell per side of the matrix
#' @param radius int. Gaps radius
#' @param probability double. Gaps probability
#' 
#' @examples
#' forestgapdynamics(20, 2, 0.01)
#' 
#' @export
forestgapdynamics <- function(grid, radius, probability) {
    .Call(`_ecoevosimulator_forestgapdynamics`, grid, radius, probability)
}

#' @title Build gradient
#' 
#' @description
#' C++ code to build environmental gradients
#' 
#' @name build_gradient
#' 
#' @param gradientlim double. Environmental gradient size
#' @param length int. Number of cells
#' 
#' @examples
#' product_environmental_matrix(10, 10)
#' 
#' @export
product_environmental_matrix <- function(gradientlim, length) {
    .Call(`_ecoevosimulator_product_environmental_matrix`, gradientlim, length)
}

#' @title simulator C++
#' 
#' @description
#' Eco-evolutionary simulator in C++.
#' 
#' @name simulatorCpp
#' 
#' @param grid int. Number of cell per side of the environmental matrix
#' @param Ngen int. Number of generations
#' @param muG double. Mean of genetic values
#' @param sigmaG double. Variance of genetic values
#' @param muE double. Mean of environmental values
#' @param sigmaE double. Variance of environmental values
#' @param Elim double. Environmental gradient size
#' @param seedlings int. Number of seedlings per cell
#' @param dispersal int. Dispersal distance in cells
#' @param gapradius int. Gaps radius
#' @param fallprobability double. Gaps probability
#' @param death double. Death probabilty
#' @param viability_deterministic bool. Deterministic or probabilistic vaibility
#' 
#' @return A lsit.
#' 
#' @examples
#' simulatorCpp()
#' 
#' @export
simulatorCpp <- function(grid = 20L, Ngen = 50L, muG = 0, sigmaG = 1, muE = 0, sigmaE = 1, Elim = 5, seedlings = 4L, dispersal = 1L, gapradius = 2L, fallprobability = 0.01, death = 0.1, viability_deterministic = TRUE) {
    .Call(`_ecoevosimulator_simulatorCpp`, grid, Ngen, muG, sigmaG, muE, sigmaE, Elim, seedlings, dispersal, gapradius, fallprobability, death, viability_deterministic)
}

